name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node_version: 23.10.x
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'

      - name: Install
        run: npm ci --force

      - name: Build
        run: npm run build

      - name: Test
        run: echo "Enable tests"

      - name: Lint
        run: echo "Enable lint"
