name: Release patch

on:
  workflow_dispatch:

permissions:
  contents: write # needed to push commit and tag

jobs:
  release-patch:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      node_version: 23.10.x

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'

      - name: Install
        run: npm ci --force

      - name: Configure Git author
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump patch version
        run: |
          npm version patch -m "HOTFIX: %s"

      - name: Build
        run: npm run build:all

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --yes --no-private

      - name: Push commit and tag
        run: |
          git push origin HEAD
          git push origin --tags
